name: CI/CD Workflow

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy-prod:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Linter
              run: npm run lint

            - name: Build and Push Docker Image
              run: |
                  docker build -t your-docker-username/your-node-app:development .
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker push your-docker-username/your-node-app:development

            - name: Deploy PROD
              run: |
                  ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} "docker-compose -f ${{ secrets.REMOTE_PATH_COMPOSER }}/docker-compose.yml pull
                  ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} "docker-compose -f /path/to/docker-compose.yml up -d"
